Removed cancellation file

diff --git a/.github/workflows/automated-tests.yml b/.github/workflows/automated-tests.yml
--- a/.github/workflows/automated-tests.yml
+++ b/.github/workflows/automated-tests.yml
@@ -38,10 +38,15 @@ jobs:
                   # Save test result status to a file
                   echo "$test_result" > test_results/test_passed_flag.txt
 
-                  # Print result based on test status
-                  if [ "$test_result" -eq 0 ]; then
-                      echo "All tests passed."
-                  else
-                      echo "Some tests failed."
-                  fi
+                  # Fail deployment if tests fail
+                  # if [ "$test_result" -ne 0 ]; then
+                  #     echo "Tests failed"
+                  #     exit 1
+                  # fi
               shell: bash
+
+            - name: Upload test results
+              uses: actions/upload-artifact@v2
+              with:
+                  name: test-results
+                  path: test_results
diff --git a/.github/workflows/w3c-validation.yml b/.github/workflows/w3c-validation.yml
--- a/.github/workflows/w3c-validation.yml
+++ b/.github/workflows/w3c-validation.yml
@@ -76,4 +76,21 @@ jobs:
                   done
                   echo "$validation_failed" > validation_results/css_validation_failed_flag.txt
 
+            - name: Upload validation results
+              uses: actions/upload-artifact@v2
+              with:
+                  name: validation-results
+                  path: validation_results
+
+            - name: Fail if validation issues found
+              run: |
+                  html_validation_failed=$(cat validation_results/html_validation_failed_flag.txt)
+                  css_validation_failed=$(cat validation_results/css_validation_failed_flag.txt)
+                  if [ "$html_validation_failed" -eq 1 ] || [ "$css_validation_failed" -eq 1 ]; then
+                      echo "Validation issues found. Failing the workflow."
+                      exit 1
+                  else
+                      echo "Validation successful."
+                  fi
+
             
