Fixed workflows yml for all test files

diff --git a/.github/workflows/automated-tests.yml b/.github/workflows/automated-tests.yml
--- a/.github/workflows/automated-tests.yml
+++ b/.github/workflows/automated-tests.yml
@@ -48,7 +48,7 @@ jobs:
 
             - name: Run tests with pytest-playwright
               run: |
-                  pytest tests/test_index.py --json-report --json-report-file=test-results.json
+                  pytest tests/test*.py --json-report --json-report-file=test-results.json
               continue-on-error: true
 
             - name: Upload test results
@@ -57,11 +57,18 @@ jobs:
                   name: test-results
                   path: test-results.json
 
+            - name: Check if any tests ran
+              run: |
+                  if grep -q '"total": 0,' test-results.json; then
+                    echo "No tests were run"
+                    exit 1
+                  fi
+
             - name: Check test results
               run: |
                   if grep -q '"failed":' test-results.json; then
-                      echo "Tests failed"
-                      exit 1
+                    echo "Tests failed"
+                    exit 1
                   else
-                      echo "Tests passed"
+                    echo "Tests passed"
                   fi
